module Evergreen.Migrate.V16 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V11.Types
import Evergreen.V16.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V11.Types.FrontendModel -> ModelMigration Evergreen.V16.Types.FrontendModel Evergreen.V16.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V11.Types.BackendModel -> ModelMigration Evergreen.V16.Types.BackendModel Evergreen.V16.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V11.Types.FrontendMsg -> MsgMigration Evergreen.V16.Types.FrontendMsg Evergreen.V16.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V11.Types.ToBackend -> MsgMigration Evergreen.V16.Types.ToBackend Evergreen.V16.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V11.Types.BackendMsg -> MsgMigration Evergreen.V16.Types.BackendMsg Evergreen.V16.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V11.Types.ToFrontend -> MsgMigration Evergreen.V16.Types.ToFrontend Evergreen.V16.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_FrontendModel : Evergreen.V11.Types.FrontendModel -> Evergreen.V16.Types.FrontendModel
migrate_Types_FrontendModel old =
    { game = old.game
    , existingGame = Nothing
    , selectedCard = old.selectedCard
    , enteredGameCode = old.enteredGameCode
    , cardOptions = old.cardOptions
    , hideStats = old.hideStats
    , device = old.device
    , key = old.key
    }


migrate_Types_FrontendMsg : Evergreen.V11.Types.FrontendMsg -> Evergreen.V16.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V11.Types.NoOpFrontendMsg ->
            Evergreen.V16.Types.NoOpFrontendMsg

        Evergreen.V11.Types.GameCreated ->
            Evergreen.V16.Types.GameCreated

        Evergreen.V11.Types.CardSelected p0 p1 ->
            Evergreen.V16.Types.CardSelected (p0 |> migrate_Types_Game) p1

        Evergreen.V11.Types.GameCodeEntered p0 ->
            Evergreen.V16.Types.GameCodeEntered p0

        Evergreen.V11.Types.RequestGame ->
            Evergreen.V16.Types.RequestGame

        Evergreen.V11.Types.LeftGame p0 ->
            Evergreen.V16.Types.LeftGame (p0 |> migrate_Types_GameId)

        Evergreen.V11.Types.ToggleStats ->
            Evergreen.V16.Types.ToggleStats

        Evergreen.V11.Types.ResetGame p0 ->
            Evergreen.V16.Types.ResetGame (p0 |> migrate_Types_Game)

        Evergreen.V11.Types.ChooseCardOptions p0 ->
            Evergreen.V16.Types.ChooseCardOptions p0

        Evergreen.V11.Types.CopyCodeToClipboard p0 ->
            Evergreen.V16.Types.CopyCodeToClipboard (p0 |> migrate_Types_Game)

        Evergreen.V11.Types.GotWindowDimensions p0 p1 ->
            Evergreen.V16.Types.GotWindowDimensions p0 p1


migrate_Types_Game : Evergreen.V11.Types.Game -> Evergreen.V16.Types.Game
migrate_Types_Game old =
    old


migrate_Types_GameId : Evergreen.V11.Types.Game -> Evergreen.V16.Types.GameId
migrate_Types_GameId old =
    old |> .code


migrate_Types_ToBackend : Evergreen.V11.Types.ToBackend -> Evergreen.V16.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V11.Types.NoOpToBackend ->
            Evergreen.V16.Types.NoOpToBackend

        Evergreen.V11.Types.CreateGame p0 ->
            Evergreen.V16.Types.CreateGame p0

        Evergreen.V11.Types.JoinGame p0 ->
            Evergreen.V16.Types.JoinGame p0

        Evergreen.V11.Types.LeaveGame p0 ->
            Evergreen.V16.Types.LeaveGame p0

        Evergreen.V11.Types.UpdatePlayerCard p0 p1 ->
            Evergreen.V16.Types.UpdatePlayerCard p0 p1

        Evergreen.V11.Types.ResetGameCards p0 ->
            Evergreen.V16.Types.ResetGameCards p0


migrate_Types_ToFrontend : Evergreen.V11.Types.ToFrontend -> Evergreen.V16.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V11.Types.NoOpToFrontend ->
            Evergreen.V16.Types.NoOpToFrontend

        Evergreen.V11.Types.CreatedGameReceived p0 ->
            Evergreen.V16.Types.CreatedGameReceived p0

        Evergreen.V11.Types.GameReceived p0 ->
            Evergreen.V16.Types.GameReceived p0

        Evergreen.V11.Types.GameReset p0 ->
            Evergreen.V16.Types.GameReset p0
