module Evergreen.Migrate.V5 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Element exposing (DeviceClass(..), Orientation(..))
import Evergreen.V4.Types
import Evergreen.V5.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V4.Types.FrontendModel -> ModelMigration Evergreen.V5.Types.FrontendModel Evergreen.V5.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V4.Types.BackendModel -> ModelMigration Evergreen.V5.Types.BackendModel Evergreen.V5.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V4.Types.FrontendMsg -> MsgMigration Evergreen.V5.Types.FrontendMsg Evergreen.V5.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V4.Types.ToBackend -> MsgMigration Evergreen.V5.Types.ToBackend Evergreen.V5.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V4.Types.BackendMsg -> MsgMigration Evergreen.V5.Types.BackendMsg Evergreen.V5.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V4.Types.ToFrontend -> MsgMigration Evergreen.V5.Types.ToFrontend Evergreen.V5.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V4.Types.FrontendModel -> Evergreen.V5.Types.FrontendModel
migrate_Types_FrontendModel old =
    { room = old.room
    , scoreSelection = old.scoreSelection
    , enteredRoomCode = old.enteredRoomCode
    , pointOptions = old.pointOptions
    , hideStats = old.hideStats
    , device = { class = Desktop, orientation = Landscape }
    }


migrate_Types_FrontendMsg : Evergreen.V4.Types.FrontendMsg -> Evergreen.V5.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V4.Types.NoOpFrontendMsg ->
            Evergreen.V5.Types.NoOpFrontendMsg

        Evergreen.V4.Types.PlanningRoomCreated ->
            Evergreen.V5.Types.PlanningRoomCreated

        Evergreen.V4.Types.ScoreSelected p0 p1 ->
            Evergreen.V5.Types.ScoreSelected (p0 |> migrate_Types_Room) p1

        Evergreen.V4.Types.RoomCodeEntered p0 ->
            Evergreen.V5.Types.RoomCodeEntered p0

        Evergreen.V4.Types.RequestPlanningRoom ->
            Evergreen.V5.Types.RequestPlanningRoom

        Evergreen.V4.Types.LeftPlanningRoom ->
            Evergreen.V5.Types.LeftPlanningRoom

        Evergreen.V4.Types.ToggleStats ->
            Evergreen.V5.Types.ToggleStats

        Evergreen.V4.Types.ResetRoom p0 ->
            Evergreen.V5.Types.ResetRoom (p0 |> migrate_Types_Room)

        Evergreen.V4.Types.ChoosePointOptions p0 ->
            Evergreen.V5.Types.ChoosePointOptions p0

        Evergreen.V4.Types.CopyKeyToClipboard p0 ->
            Evergreen.V5.Types.CopyKeyToClipboard (p0 |> migrate_Types_Room)


migrate_Types_Room : Evergreen.V4.Types.Room -> Evergreen.V5.Types.Room
migrate_Types_Room old =
    old
