module Evergreen.Migrate.V6 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V5.Types
import Evergreen.V6.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V5.Types.FrontendModel -> ModelMigration Evergreen.V6.Types.FrontendModel Evergreen.V6.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V5.Types.BackendModel -> ModelMigration Evergreen.V6.Types.BackendModel Evergreen.V6.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V5.Types.FrontendMsg -> MsgMigration Evergreen.V6.Types.FrontendMsg Evergreen.V6.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V5.Types.ToBackend -> MsgMigration Evergreen.V6.Types.ToBackend Evergreen.V6.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V5.Types.BackendMsg -> MsgMigration Evergreen.V6.Types.BackendMsg Evergreen.V6.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V5.Types.ToFrontend -> MsgMigration Evergreen.V6.Types.ToFrontend Evergreen.V6.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


mapRoomToGame : Evergreen.V5.Types.Room -> Evergreen.V6.Types.Game
mapRoomToGame room =
    { code = room.key
    , cardOptions = room.pointOptions
    , playedCards = room.points
    }


migrate_Types_BackendModel : Evergreen.V5.Types.BackendModel -> Evergreen.V6.Types.BackendModel
migrate_Types_BackendModel old =
    Dict.map (\_ value -> mapRoomToGame value) old


migrate_Types_FrontendModel : Evergreen.V5.Types.FrontendModel -> Evergreen.V6.Types.FrontendModel
migrate_Types_FrontendModel old =
    { game = Maybe.map mapRoomToGame old.room
    , selectedCard = old.scoreSelection
    , enteredGameCode = old.enteredRoomCode
    , cardOptions = old.pointOptions
    , hideStats = old.hideStats
    , device = old.device
    }


migrate_Types_FrontendMsg : Evergreen.V5.Types.FrontendMsg -> Evergreen.V6.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V5.Types.NoOpFrontendMsg ->
            Evergreen.V6.Types.NoOpFrontendMsg

        Evergreen.V5.Types.PlanningRoomCreated ->
            Evergreen.V6.Types.GameCreated

        Evergreen.V5.Types.ScoreSelected p0 p1 ->
            Evergreen.V6.Types.CardSelected (mapRoomToGame p0) p1

        Evergreen.V5.Types.RoomCodeEntered p0 ->
            Evergreen.V6.Types.GameCodeEntered p0

        Evergreen.V5.Types.RequestPlanningRoom ->
            Evergreen.V6.Types.RequestGame

        Evergreen.V5.Types.LeftPlanningRoom ->
            Evergreen.V6.Types.LeftGame

        Evergreen.V5.Types.ToggleStats ->
            Evergreen.V6.Types.ToggleStats

        Evergreen.V5.Types.ResetRoom p0 ->
            Evergreen.V6.Types.ResetGame (mapRoomToGame p0)

        Evergreen.V5.Types.ChoosePointOptions p0 ->
            Evergreen.V6.Types.ChooseCardOptions p0

        Evergreen.V5.Types.CopyKeyToClipboard p0 ->
            Evergreen.V6.Types.CopyCodeToClipboard (mapRoomToGame p0)

        Evergreen.V5.Types.GotDimensions p0 p1 ->
            Evergreen.V6.Types.GotWindowDimensions p0 p1


migrate_Types_ToFrontend : Evergreen.V5.Types.ToFrontend -> Evergreen.V6.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V5.Types.NoOpToFrontend ->
            Evergreen.V6.Types.NoOpToFrontend

        Evergreen.V5.Types.PlanningRoomReceived p0 ->
            Evergreen.V6.Types.GameReceived (Maybe.map mapRoomToGame p0)
